### ISSUE TITLE
PandoraBootstrap启动antx-autoconfig-1.2-jdk9-3.jar加载失败

### ISSUE THREAD

**Issue by yangshun18612694056** [aliyun/alibabacloud-microservice-demo#11]
fail to download http://mvnrepo.alibaba-inc.com/mvn/repository/com/alibaba/citrus/tool/antx-autoconfig/1.2-jdk9-3/antx-autoconfig-1.2-jdk9-3.jar to C:\Users\admin\.autoconf\autoconf-1.2-jdk9-3.jar
C:\Users\admin\.autoconf\autoconf-1.2-jdk9-3.jar doesn't exist.

**Comment by tomboxfan** [comment]
same here.

**Comment by LK-13579** [comment]
same

**Comment by 2425691371** [comment]
运行测试普通的调用，同样问题，楼主解决了吗？

**Comment by 1715640858** [comment]
same
autoconf-1.2-jdk9-3.jar doesn't exist at first
Nullpoint at last:
[developer.aliyun.com/ask/313119](https://developer.aliyun.com/ask/313119)

Give us same tips, Please!

**Comment by ralf0131** [comment]
autoconfig is way too old to use, the antx-autoconfig-1.2-jdk9-3 is supposed to be in Alibaba's internal maven repository. 
We recommend to use Spring Cloud and Apache Dubbo to build your microservice applications. Why do you need to use pandora boot?

**Comment by 1715640858** [comment]
We just do it as the guid of 
https://help.aliyun.com/document_detail/100084.html
and
https://github.com/aliyun/alibabacloud-microservice-demo.git
