### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by sunrui1225** [aliyun/alibabacloud-microservice-demo#29]
我在执行 docker-compose build的时候显示以下error，有遇到过这个问题的同学吗？
环境：MacOS Catalina 
docker desktop communtiy version 2.4.0.0 stable

Building checkoutservice
Step 1/6 : FROM  openjdk:8-jre-alpine
 ---> f7a292bbb70c
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> eb521812e776
Step 3/6 : COPY /checkoutservice-provider/target/checkoutservice-provider-0.0.1-SNAPSHOT.jar /app
ERROR: Service 'checkoutservice' failed to build : COPY failed: stat /var/lib/docker/tmp/docker-builder245776263/checkoutservice-provider/target/checkoutservice-provider-0.0.1-SNAPSHOT.jar: no such file or directory

**Comment by sunrui1225** [comment]
已经解决

**Comment by liangminghan0228** [comment]
请问怎么解决的
