### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by huang-tie** [aliyun/alibabacloud-microservice-demo#34]
http://123.56.245.71:8080

**Comment by huang-tie** [comment]
这个演示项目的地址打不开，能说下吗？

**Comment by flystar32** [comment]
您好，由于资源/经费/安全的原因，演示地址目前暂时停止提供维护

您可以通过在工程根目录下执行 `helm install microservice-demo helm-chart --namespace default ` 来在 K8s 集群中直接拉起 Demo 应用
